layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: "carlos.msouza"
  # keybase: your_username
  linkedin: "carlos-medeiros-864424179"
  # mastodon: your_username
  medium: "carlosmedeirosdesouza"
  # stackoverflow: your_user_id
  telegram: mdscarlos
  # twitter: "_carlosmds"
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_usernames

topics:
  - name: Python
    web_url: https://docs.python.org/3/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/115px-Python-logo-notext.svg.png?20220821155029 

  - name: Solidity
    web_url: https://docs.soliditylang.org/en/v0.8.18/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Solidity_logo.svg/1200px-Solidity_logo.svg.png

  - name: OpenAI
    web_url: https://openai.com/api/
    image_url: https://logosandtypes.com/wp-content/uploads/2022/07/openai.svg
