layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: https://www.instagram.com/carlos.msouza
  # keybase: your_username
  linkedin: https://www.linkedin.com/in/carlos-medeiros-864424179
  # mastodon: your_username
  medium: https://medium.com/@carlosmedeirosdesouza
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: https://twitter.com/_carlosmds
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Ansible
    web_url: https://docs.ansible.com/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Ansible_logo.svg/256px-Ansible_logo.svg.png

  - name: Kubernetes
    web_url: https://kubernetes.io/pt-br/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/617px-Kubernetes_logo_without_workmark.svg.png?20190926210707

  - name: OpenAI
    web_url: https://openai.com/api/
    image_url: https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg
